repos:
  - repo: local
    hooks:
      - id: rubocop -a
        name: Run rubocop -a
        description: This hook runs the rubocop linter.
        entry: rubocop -a
        language: system
        fail_fast: true
        exclude: .pre-commit-config.yaml
