AllCops:
  NewCops: enable
  Exclude:
    - "lib/tasks/auto_annotate_models.rake"
    - "bin/**/*"
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "config/environments/*.rb"
    - "vendor/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 10

Metrics/CyclomaticComplexity:
  Max: 10

RSpec/MultipleExpectations:
  Max: 20

RSpec/ExampleLength:
  Max: 50

RSpec/NestedGroups:
  Max: 5

Layout/LineLength:
  Max: 180

RSpec/AnyInstance:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

require:
  - rubocop-rspec
  - rubocop-rails
  - rubocop-factory_bot
