name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.4' # should correspond to .ruby-version

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run Rubocop (format check)
      run: bundle exec rubocop --parallel
  coverage:
    runs-on: ubuntu-latest
    name: RSpec - Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.0.4' # should correspond to .ruby-version

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: matomeishi_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      USER: postgres

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Set environment variables for RSpec
      run: |
        echo '::set-env name=RAILS_ENV::test'
        echo '::set-env name=DATABASE_URL::postgres://postgres:postgres@localhost:5432/matomeishi_test'
    - name: Setup database
      run: |
        bundle exec rails db:schema:load
    - name: Run RSpec (test & coverage)
      uses: paambaati/codeclimate-action@v5.0.0
      env:
        CC_TEST_REPORTER_ID: c0d6206ec9a97dc9390ee0d1fd25f7515d96ca14fdf72a409a511c6b738a26c1
      with:
        coverageCommand: bundle exec rspec
        coverageLocations: ${{ github.workspace }}/coverage/coverage.json:simplecov
        debug: true
