name: Ruby

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ".ruby-version"
      - name: Install gems
        run: |
          gem install bundler
          gem install sorbet
          bundle install --jobs 4 --retry 3 --path=vendor/bundle
      - name: Run tests with rubocop
        run: |
          bundle exec rubocop --parallel
